# These are supported funding model platforms

github:
custom:
  - "https://link.payoneer.com/Token?t=543D18CF69384278AD9C30D1B651D638&src=dpl"
patreon: cw/amharic_tokenizer/membership
open_collective: amharic-tokenizer
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
